-- AlterTable
ALTER TABLE `PurchaseOrder` MODIFY `status` ENUM('PENDING', 'PROCESS', 'EXECUTED', 'REJECTED') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `SaleOrder` MODIFY `status` ENUM('PENDING', 'PROCESS', 'EXECUTED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
